version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai_net

  app:
    build: ./app
    container_name: ai_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis-vector
      - REDIS_PORT=6379
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral
    depends_on:
      - redis-vector
      - ollama
    networks:
      - ai_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis-vector:
    image: redis/redis-stack:latest
    container_name: redis-vector
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - ai_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - ai_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge

volumes:
  redis_data:
  grafana_data:
  ollama_data:
